### ISSUE TITLE
Docs are wrong and latest version breaks usage inside a scrollview

### ISSUE THREAD

**Issue by stuckj** [sacmii/rn-vertical-slider#89]
The latest 4.0.0 switches to using `react-native-gesture-handler` for handling scrolling of the slider. This breaks usage inside a scroll view. It also requires the outside code to stick a `<GestureHandlerRootView>` wrapper around their app.

Also, the current docs in the `README.md` are for the interface in the 3.1.1 version...they're not updated for 4.0.0.

**Comment by sacmii** [comment]
@stuckj This has been fixed in the latest version. Hence closing the issue

**Comment by stuckj** [comment]
Hmm. Still doesn't appear to work inside of a scroll view. Guess I'll stick with 3.3.1.
